server:
  port: 8080
  servlet:
    context-path: /api  # 保留你的 /api 前缀

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/wxapp_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: chaojimali.25
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-aliases-package: my.hive_back.module.*.model.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0