server:
  port: 8080
  servlet:
    context-path: /api  # 全局上下文路径，所有请求都要带 /api 前缀

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev  # 激活开发环境配置

mybatis-plus:
  type-aliases-package: my.hive_back.module.*.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    # 增加该配置：确保跳转时带上 context-path
    use-root-path: false
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true